package com.mckuai.imc;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tokenDaoConfig;
    private final DaoConfig typeDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig forumDaoConfig;

    private final TokenDao tokenDao;
    private final TypeDao typeDao;
    private final UserDao userDao;
    private final ForumDao forumDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tokenDaoConfig = daoConfigMap.get(TokenDao.class).clone();
        tokenDaoConfig.initIdentityScope(type);

        typeDaoConfig = daoConfigMap.get(TypeDao.class).clone();
        typeDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        forumDaoConfig = daoConfigMap.get(ForumDao.class).clone();
        forumDaoConfig.initIdentityScope(type);

        tokenDao = new TokenDao(tokenDaoConfig, this);
        typeDao = new TypeDao(typeDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        forumDao = new ForumDao(forumDaoConfig, this);

        registerDao(Token.class, tokenDao);
        registerDao(Type.class, typeDao);
        registerDao(User.class, userDao);
        registerDao(Forum.class, forumDao);
    }

    public void clear() {
        tokenDaoConfig.getIdentityScope().clear();
        typeDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        forumDaoConfig.getIdentityScope().clear();
    }

    public TokenDao getTokenDao() {
        return tokenDao;
    }

    public TypeDao getTypeDao() {
        return typeDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ForumDao getForumDao() {
        return forumDao;
    }

}
