package com.mckuai.imc;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.mckuai.imc.Bean.ForumInfo;

/**
 * Entity mapped to table "Forum".
 */
public class Forum {

    private Long id;
    private Integer postCount;
    private String name;
    private String cover;
    private String type;//用逗号分享的类型id

    public Forum() {
    }

    public Forum(Long id) {
        this.id = id;
    }

    public Forum(Long id, Integer postCount, String name, String cover, String type) {
        this.id = id;
        this.postCount = postCount;
        this.name = name;
        this.cover = cover;
        this.type = type;
    }

    public Forum(ForumInfo forumInfo) {
        this.id = Long.valueOf((long) forumInfo.getId());
        this.postCount = forumInfo.getTalkNum();
        this.name = forumInfo.getName();
        this.cover = forumInfo.getIcon();
        if (null != forumInfo.getIncludeType() && 0 < forumInfo.getIncludeType().size()) {
            String postType = "";
            for (Type type : forumInfo.getIncludeType()) {
                postType += type.getId() + ",";
            }
            postType = postType.substring(0, postType.length() - 2);
            this.type = postType;
        }
    }

    public ForumInfo toForumInfo() {
        return new ForumInfo(id.intValue(), name, cover, postCount, null);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPostCount() {
        return postCount;
    }

    public void setPostCount(Integer postCount) {
        this.postCount = postCount;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCover() {
        return cover;
    }

    public void setCover(String cover) {
        this.cover = cover;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }
}
