package com.mckuai.imc;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Token".
 */
public class Token {

    private Long id;
    private Integer type;
    private Long birthday;
    private Long expires;
    /**
     * Not-null value.
     */
    private String token;

    public Token() {
    }

    public Token(Long id) {
        this.id = id;
    }

    public Token(Long id, Integer type, Long birthday, Long expires, String token) {
        this.id = id;
        this.type = type;
        this.birthday = birthday;
        this.expires = expires;
        this.token = token;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Long getBirthday() {
        return birthday;
    }

    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    public Long getExpires() {
        return expires;
    }

    public void setExpires(Long expires) {
        this.expires = expires;
    }

    /** Not-null value. */
    public String getToken() {
        return token;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setToken(String token) {
        this.token = token;
    }

}
