package com.mckuai.imc;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "Token".
 */
public class Token {

    private Long id;
    private Integer type;//0:自有;1:QQ;2:微信;3:融云
    private Integer userId;//用户id
    private Long birthday;
    private Long expires;
    /**
     * Not-null value.
     */
    private String token;

    public Token() {
    }

    public Token(Long id) {
        this.id = id;
    }

    /**
     * 构造一个Token对象
     *
     * @param id       id;
     * @param id       用户Id;
     * @param type     类型
     * @param birthday 创建日期
     * @param expires  截止有效期
     * @param token    token
     */
    public Token(Long id, Integer userId, Integer type, Long birthday, long expires, String token) {
        this.id = id;
        this.type = type;
        if (null == birthday) {
            long time = System.currentTimeMillis();
            time = (time - time % 1000) / 1000;
            this.birthday = time;
        } else {
            this.birthday = birthday;
        }
        this.expires = birthday + expires;
        this.token = token;
        this.userId = userId;
    }

    public Token(Integer type, Long birthday, long expires, String token) {
        this.id = null;
        this.type = type;
        if (null == birthday) {
            long time = System.currentTimeMillis();
            time = (time - time % 1000) / 1000;
            this.birthday = time;
        } else {
            this.birthday = birthday;
        }
        this.expires = birthday + expires;
        this.token = token;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Long getBirthday() {
        return birthday;
    }

    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    public Long getExpires() {
        return expires;
    }

    public void setExpires(Long expires) {
        this.expires = expires;
    }

    /** Not-null value. */
    public String getToken() {
        return token;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setToken(String token) {
        this.token = token;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public boolean isTokenSurvival() {
        return System.currentTimeMillis() < (expires * 1000);
    }

}
